version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '3000:3000'
    environment:
      PRISMA_CONFIG: |
        port: 3000
        databases:
          default:
            connector: mysql
            host:
            port: 3000
            user: root
            password:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
#Reconfigure it later when everything is ready is ready